Module Uni_CMD
    Public HDLC_HEADER As Integer = &H7E
    Public HDLC_ESCAPE As Integer = &H7D
    Public Enum BSL
        CMD_CONNECT = &H0

        CMD_START_DATA = &H1
        CMD_MIDST_DATA = &H2
        CMD_END_DATA = &H3
        CMD_EXEC_DATA = &H4

        CMD_NORMAL_RESET = &H5
        CMD_READ_FLASH = &H6
        CMD_READ_CHIP_TYPE = &H7
        CMD_READ_NVITEM = &H8
        CMD_CHANGE_BAUD = &H9
        CMD_ERASE_FLASH = &HA
        CMD_REPARTITION = &HB
        CMD_READ_FLASH_TYPE = &HC
        CMD_READ_FLASH_INFO = &HD
        CMD_READ_SECTOR_SIZE = &HF
        CMD_READ_START = &H10
        CMD_READ_MIDST = &H11
        CMD_READ_END = &H12

        CMD_KEEP_CHARGE = &H13
        CMD_EXTTABLE = &H14
        CMD_READ_FLASH_UID = &H15
        CMD_READ_SOFTSIM_EID = &H16
        CMD_POWER_OFF = &H17
        CMD_CHECK_ROOT = &H19
        CMD_READ_CHIP_UID = &H1A
        CMD_ENABLE_WRITE_FLASH = &H1B
        CMD_ENABLE_SECUREBOOT = &H1C
        CMD_IDENTIFY_START = &H1D
        CMD_IDENTIFY_END = &H1E
        CMD_READ_CU_REF = &H1F
        CMD_READ_REFINFO = &H20
        CMD_DISABLE_TRANSCODE = &H21
        CMD_WRITE_DATETIME = &H22
        CMD_CUST_DUMMY = &H23
        CMD_READ_RF_TRANSCEIVER_TYPE = &H24
        CMD_SET_DEBUGINFO = &H25
        CMD_DDR_CHECK = &H26
        CMD_SELF_REFRESH = &H27
        CMD_WRITE_RAW_DATA_ENABLE = &H28
        CMD_READ_NAND_BLOCK_INFO = &H29
        CMD_SET_FIRST_MODE = &H2A
        CMD_READ_PARTITION = &H2D
        CMD_DLOAD_RAW_START = &H31
        CMD_WRITE_FLUSH_DATA = &H32
        CMD_DLOAD_RAW_START2 = &H33
        CMD_READ_LOG = &H35
        CMD_CHECK_BAUD = &H7E
        CMD_END_PROCESS = &H7F
        REP_ACK = &H80
        REP_VER = &H81
        REP_INVALID_CMD = &H82
        REP_UNKNOW_CMD = &H83
        REP_OPERATION_FAILED = &H84
        REP_NOT_SUPPORT_BAUDRATE = &H85
        REP_DOWN_NOT_START = &H86
        REP_DOWN_MULTI_START = &H87
        REP_DOWN_EARLY_END = &H88
        REP_DOWN_DEST_ERROR = &H89
        REP_DOWN_SIZE_ERROR = &H8A
        REP_VERIFY_ERROR = &H8B
        REP_NOT_VERIFY = &H8C
        PHONE_NOT_ENOUGH_MEMORY = &H8D
        PHONE_WAIT_INPUT_TIMEOUT = &H8E
        PHONE_SUCCEED = &H8F
        PHONE_VALID_BAUDRATE = &H90
        PHONE_REPEAT_CONTINUE = &H91
        PHONE_REPEAT_BREAK = &H92
        REP_READ_FLASH = &H93
        REP_READ_CHIP_TYPE = &H94
        REP_READ_NVITEM = &H95
        REP_INCOMPATIBLE_PARTITION = &H96
        REP_SIGN_VERIFY_ERROR = &HA6
        REP_READ_CHIP_UID = &HAB
        REP_READ_PARTITION = &HBA
        REP_READ_LOG = &HBB
        REP_UNSUPPORTED_COMMAND = &HFE
        REP_NOT_ENABLE_WRITE_FLASH = &HAC
    End Enum

End Module
